let liveSocket,liveContext,liveStream,liveNode,liveSource,playingAt=0;
function liveWsUrl(){return `${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/live`;}
function floatToPcm16(input){const buffer=new ArrayBuffer(input.length*2),view=new DataView(buffer);for(let i=0;i<input.length;i++){const value=Math.max(-1,Math.min(1,input[i]));view.setInt16(i*2,value<0?value*32768:value*32767,true);}return new Uint8Array(buffer);}
function base64(bytes){let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary);}
function decodeBase64(value){const binary=atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes;}
function playPcm16(value){const bytes=decodeBase64(value),samples=new Float32Array(bytes.length/2),view=new DataView(bytes.buffer);for(let i=0;i<samples.length;i++)samples[i]=view.getInt16(i*2,true)/32768;const audio=liveContext.createBuffer(1,samples.length,24000);audio.copyToChannel(samples,0);const source=liveContext.createBufferSource();source.buffer=audio;source.connect(liveContext.destination);playingAt=Math.max(liveContext.currentTime,playingAt);source.start(playingAt);playingAt+=audio.duration;}
async function startLive(){liveContext=new AudioContext({sampleRate:24000});liveStream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true}});liveSocket=new WebSocket(liveWsUrl());liveSocket.onopen=()=>{document.querySelector('#livePanel').classList.remove('hidden');document.querySelector('#liveStatus').textContent='正在聆听，可随时说话或打断';liveSource=liveContext.createMediaStreamSource(liveStream);liveNode=liveContext.createScriptProcessor(2048,1,1);liveNode.onaudioprocess=event=>{if(liveSocket.readyState===WebSocket.OPEN)liveSocket.send(JSON.stringify({type:'audio.append',audio:base64(floatToPcm16(event.inputBuffer.getChannelData(0)))}));};liveSource.connect(liveNode);liveNode.connect(liveContext.destination);};liveSocket.onmessage=message=>{const event=JSON.parse(message.data);if(event.type==='audio.delta')playPcm16(event.audio);if(event.type==='transcript.delta'){document.querySelector('#result').classList.remove('hidden');document.querySelector('#answer').textContent+=event.text;}if(event.type==='input.transcript')document.querySelector('#liveStatus').textContent=`你说：${event.text}`;if(event.type==='error')document.querySelector('#liveStatus').textContent=event.message;};liveSocket.onclose=stopLive;}
function interruptLive(){if(liveSocket?.readyState===WebSocket.OPEN)liveSocket.send(JSON.stringify({type:'interrupt'}));playingAt=liveContext?.currentTime||0;}
function stopLive(){liveNode?.disconnect();liveSource?.disconnect();liveStream?.getTracks().forEach(track=>track.stop());if(liveSocket?.readyState===WebSocket.OPEN)liveSocket.close();document.querySelector('#livePanel').classList.add('hidden');}
window.PoetryLive={start:startLive,interrupt:interruptLive,stop:stopLive};
